json.id @trip.id
json.host_firstname @trip.host.firstname
json.host_lastname @trip.host.lastname
json.host_pic @trip.host.image
json.host_id @trip.host_id
json.traveler_firstname @trip.traveler.firstname
json.traveler_lastname @trip.traveler.lastname
json.traveler_pic asset_path(@trip.traveler.image.url)
json.traveler_id @trip.user_id
json.dates @trip.dates
json.status @trip.status
json.message @trip.message
