json.extract! @listing,
              :id,
              :firstname,
              :lastname,
              :location,
              :city,
              :about,
              :hosting,
              :languages,
              :country,
              :picture
